### ISSUE TITLE
test-osd issus

### ISSUE THREAD

**Issue by thesues** [journeymidnight/nentropy#1]
@chenji-kael 

1. test-osd takes up to 4GB memory, there is something wrong with it.

2. too many message when test-osd is running..

> === RUN   TestUnAlignedWriteAndRead_rewritepart_crossstripe_differentoffset
> 32s
> 211
> read previous stripe at offset 0, got 0 
> 32s
> 212
> add leading 1 zeros for (prevLen, offsetRem) aka (0, 1)
> 32s
> 213
> using 7 bytes for this stripe 
> 32s
> 214
> full stripe at offset: 8

WTF?

**Comment by wuxingyi** [comment]
1. the oom problem is triggered by badger. When closing a badger instance, a flush is conducted, badger creates a very big buffer(96MB) for each instance(which is hard coded), when closing 100 instances, 9GB memory usage triggered the oom.
```
// NewTableBuilder makes a new TableBuilder.
func NewTableBuilder() *Builder {
	return &Builder{
		keyBuf:     newBuffer(32 << 20),
		buf:        newBuffer(64 << 20),
		prevOffset: math.MaxUint32, // Used for the first element!
	}
}
```
I already made a pull request :https://github.com/dgraph-io/badger/pull/281, which will save much memory because we can use much smaller table size.

2. message will output to log file soon.
